version: "3.9"

services:
  server:
    build: ../app
    container_name: server
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ../app:/usr/src/app
    env_file:
      - ../app/.env.dev
    depends_on:
      - db
  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    volumes:
      - ../app/.config/db:/var/lib/mysql
